In [1]:
import numpy as np

In [196]:
def find(y,x,matx,sol):
    if y>=0 and x>=0:
        
        matx[y,x]=1

        print('Position',y,x)

        print('matrix \n',matx)
        print('----------------')
    #right
        if 0 <= y+1 <= n-1 and x<=n-1 and matx[y+1,x]== 0:
            matx[y+1,x] = 1
            sol.append('right')
            return find(y+1,x,matx,sol)
    #down        
        elif 0 <= x+1 <= n-1 and y<=n-1 and matx[y,x+1]==0:
            matx[y,x+1]= 1
            sol.append('down')
            return find(y,x+1,matx,sol)

    #diagonal upleft
        elif 0 <= y-1<=n-1 and x-1<=n-1 and matx[y-1,x-1]==0:
            matx[y-1,x-1]= 1
            sol.append('diagonal upper left')
            return find(y-1,x-1,matx,sol)

        elif np.array_equal(matx,np.ones((n,n))):

            print('***************** This is a solution*****************',
                '\n..................................................',
                '\n** Starting position=',a,b,'\n',
                  '**Steps = ',sol,'**\n',
                  '******************************************************') 
        else:
            print('try other')


In [202]:
n = 3
for a in range(0,n):
    for b in range(0,n):
                print(a,b) 
                mat = np.zeros((n,n))
                solu = ['a']
                print('------------------------------------------------------------------------------------')
                print('Trying for y=',a,'and x=',b)
                print('------------------------------------------------------------------------------------')
                find(a,b,mat,solu)
                print('-------------------------')

0 0
------------------------------------------------------------------------------------
Trying for y= 0 and x= 0
------------------------------------------------------------------------------------
Position 0 0
matrix 
 [[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
----------------
Position 1 0
matrix 
 [[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
----------------
Position 2 0
matrix 
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
----------------
Position 2 1
matrix 
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 0.]]
----------------
Position 2 2
matrix 
 [[1. 0. 0.]
 [1. 0. 0.]
 [1. 1. 1.]]
----------------
Position 1 1
matrix 
 [[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
----------------
Position 1 2
matrix 
 [[1. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------------
Position 0 1
matrix 
 [[1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------------
Position 0 2
matrix 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
----------------
***************** This is a solution***************** 
.................................................. 
** Startin